### PR TITLE
replace Python 3 incompatible `zope.interface.implements` by `zope.interface.implementer`'

### LINKED ISSUE #4: Avoid Python 3 incompatible `implements`
`five.formlib` is still using the Python 3 incompatible `zope.interface.implements`.

### PR DESCRIPTION
**Pull request by d-maurer**
Fixes #4

### CODE REVIEW

**Comment by ale-rt** [comment]
Thanks!

**Comment by icemac** [comment]
@d-maurer The policy in the zopefoundation repositories is that the creator of a pull request merges his own code. To be able to do so, you have to sign the [Zope contributor agreement](https://github.com/zopefoundation/developer_docs/raw/master/source/Zope_Foundation_Committer_Agreement-20181008.pdf) and so obtain write access to these repositories. I think you singed the agreement years ago. But how can I confirm that the login @d-maurer actually belongs to the person I have in mind?

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-1-14 12:21 +0000:
>@d-maurer The policy in the zopefoundation repositories is that the creator of a pull request merges his own code. To be able to do so, you have to sign the [Zope contributor agreement](https://github.com/zopefoundation/developer_docs/raw/master/source/Zope_Foundation_Committer_Agreement-20181008.pdf) and so obtain write access to these repositories. I think you singed the agreement years ago. But how can I confirm that the login @d-maurer actually belongs to the person I have in mind?

Indeed, I have already signed the "Zope contributor agreement" -- more
than a decade ago. At that time, I have been employee of the
Haufe Mediengruppe in Freiburg and have developped (among many other
things) two Zope based editorial systems - one for use in the
internet site (based on CMFCore/CMFDefault) and one for the production
system based on "PySP" and "SGML" (essentially using
"Products.ManagableIndex", "Products.AdvancedQuery"
and "dm.incrementalsearch").

I am also the author of "Products.ManagableIndex" - and we have
had  private email communication about this package. This
private communication is something only we two should know about;
thus, it might convince you that I might indeed be the person you
have in mind.
>
>--
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zopefoundation/five.formlib/pull/5#issuecomment-453986879
--
Dieter

**Comment by icemac** [comment]
@d-maurer  wrote:
[…]
> It might convince you that I might indeed be the person you have in mind.

I'm convinced. I invited you to the `zopefoundation` repositories. (GitHub should have sent you an e-mail.) Welcome back, Dieter.

After accepting the GitHub invitation you should be able to merge this PR yourself.

**Comment by d-maurer** [comment]
The test suite still has many Python 3 incompatibilities -- working on them.

**Comment by icemac** [comment]
@d-maurer wrote:
> The test suite still has many Python 3 incompatibilities -- working on them.

Thank you for planning to tackle them. Meanwhile this PR could be merged as it already improves the situation without breaking anything.

**Pull request merged**
